---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^instructor/mkdocs/mkdocs.yml$
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: forbid-submodules
      # - id: name-tests-test
  - repo: https://github.com/asottile/add-trailing-comma.git
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma
        name: ensure trailing commas
        args:
          - --py36-plus
  - repo: local
    hooks:
      - id: unidecode-check
        name: check for non-ASCII characters
        entry: .local/unidecode-hook.py
        language: python
        types: [text]
        additional_dependencies: [unidecode]
        args:
          - --to-ascii
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: lint python
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.91.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
