site_name: "Cloudera Hbase NiFi Hands on Lab"
site_author: Cloudera Israel Education
copyright: 2025 Cloudera, Inc. All rights reserved.<br><a href="https://www.cloudera.com/legal/terms-and-conditions.html" target="_blank">Terms & Conditions | </a>  <a href="https://www.cloudera.com/legal/policies.html" target="_blank"> Privacy Policy and Data Policy</a>
repo_url: https://github.com/22itay/hol-nifi-hbase
repo_name: 22itay/hol-nifi-hbase

theme:
    name: material
    logo: assets/images/logo-cloudera-white.svg
    favicon: assets/images/favicon.ico
    palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
    features:
    - content.code.annotate
    - content.code.copy
    # - navigation.expand
    - navigation.indexes
    - navigation.path
    # - navigation.sections
    - navigation.footer
    - navigation.top

docs_dir: '../../content'
site_dir: './build'
# not_in_nav: |
extra_css:
  - assets/stylesheets/extra.css
use_directory_urls: false

nav:
    - Home: 
        - 'README.md'
        - Opening - Access the Environment: 'labs/lab0/README.md'
    - Labs:
        - Hbase: 
            - 'labs/hbase/README.md'
            - Lab 1 - Loading data to HBase: 'labs/hbase/lab1/README.md'
            - Lab 2 - Query the tables data: 'labs/hbase/lab2/README.md'
            - Lab 3 - HBase CRUD Operations: 'labs/hbase/lab3/README.md'
            - Lab 4 - HBase Advanced Features: 'labs/hbase/lab4/README.md'
        - NiFi:
            - 'labs/nifi/README.md'
            - Lab 1 - MiNiFi and Edge Flow Manager: 'labs/nifi/lab1/README.md'
            - Lab 2 - Schema Registry: 'labs/nifi/lab2/README.md'
            - Lab 3 - Receive Edge data in Data Flow: 'labs/nifi/lab3/README.md'
            - Lab 4 - Moving Data with NiFi DataFlow: 'labs/nifi/lab4/README.md'
            - Lab 5 - Using Kafka to Move Data Across Applications: 'labs/nifi/lab5/README.md'
            - Lab 6 - AI with NiFi DataFlow: 'labs/nifi/lab6/README.md'

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists: {}
  - toc:
      toc_depth: 3

plugins:
  - same-dir # to allow site_dir to be within docs_dir
  - search
  - markdownextradata: {}
  # - with-pdf:
  #     custom_template_path: templates
  #     debug_html: false
  #     output_path: exercise_guide.pdf
  - glightbox
  - macros

# Define values for macros here
extra:
    generator: false
    env: cldr-gre-cdp-env
    efm_datahub_name: gre-efm-dh
    smm_datahub_name: gre-smm-dh
    cod_datahub_name: cod-1eevbst1maraf
    cdf_workspace_name: cldr-gre-cdp-env
    cai_workbench_name: cldr-gre-cdp-env
